create database doctordb;
use doctordb;
INSERT INTO doctor_model (name, speciality, gender, experience, location, fees, languages, facility, hospital_visit, online_consult, profile_photo_url) VALUES
('Dr. Kathryn Hopkins', 'Cardiologist', 'Female', 6, 'Mumbai', 1000, 'Marathi,Kannada', 'Apollo Hospital', TRUE, TRUE, 'https://randomuser.me/api/portraits/women/82.jpg'),
('Dr. Mary Simmons', 'Psychiatrist', 'Male', 7, 'Bangalore', 700, 'Telugu', 'Other Clinics', FALSE, FALSE, 'https://randomuser.me/api/portraits/men/10.jpg'),
('Dr. Eric Miller', 'Nephrologist', 'Female', 28, 'Delhi', 700, 'Marathi,Kannada,Gujarati', 'Other Clinics', FALSE, TRUE, 'https://randomuser.me/api/portraits/women/10.jpg'),
('Dr. Eric Smith', 'Dermatologist', 'Female', 22, 'Bangalore', 300, 'Bengali,Oriya,Gujarati', 'Other Clinics', TRUE, TRUE, 'https://randomuser.me/api/portraits/women/77.jpg'),
('Dr. John Doe', 'ENT Specialist', 'Male', 3, 'Mumbai', 1000, 'English,Gujarati,Oriya', 'Apollo Hospital', TRUE, TRUE, 'https://randomuser.me/api/portraits/men/41.jpg'),
('Dr. Jane Doe', 'Psychiatrist', 'Female', 3, 'Mumbai', 1200, 'Telugu', 'Other Clinics', TRUE, TRUE, 'https://randomuser.me/api/portraits/women/51.jpg'),
('Dr. Clara Oswald', 'Neurologist', 'Male', 23, 'Delhi', 500, 'Marathi', 'Apollo Hospital', TRUE, TRUE, 'https://randomuser.me/api/portraits/men/49.jpg'),
('Dr. Peter Parker', 'Nephrologist', 'Male', 8, 'Pune', 1000, 'Telugu,Kannada,English', 'Apollo Hospital', TRUE, TRUE, 'https://randomuser.me/api/portraits/men/14.jpg'),
('Dr. Bruce Wayne', 'Nephrologist', 'Female', 7, 'Indore', 500, 'Punjabi', 'Apollo Hospital', TRUE, FALSE, 'https://randomuser.me/api/portraits/women/11.jpg'),
('Dr. Diana Prince', 'General Physician', 'Female', 23, 'Chennai', 500, 'Oriya,Persian,Telugu', 'Apollo Hospital', FALSE, TRUE, 'https://randomuser.me/api/portraits/women/60.jpg'),
('Dr. Steve Rogers', 'Nephrologist', 'Male', 15, 'Indore', 1200, 'Telugu,Assamese,Oriya', 'Apollo Hospital', FALSE, FALSE, 'https://randomuser.me/api/portraits/men/72.jpg'),
('Dr. Tony Stark', 'Gynecologist', 'Male', 23, 'Bangalore', 500, 'English,Urdu', 'Other Clinics', TRUE, FALSE, 'https://randomuser.me/api/portraits/men/47.jpg'),
('Dr. Natasha Romanoff', 'Nephrologist', 'Female', 7, 'Surat', 700, 'Punjabi,Hindi,Persian', 'Other Clinics', TRUE, FALSE, 'https://randomuser.me/api/portraits/women/26.jpg'),
('Dr. Stephen Strange', 'Gynecologist', 'Female', 11, 'Bangalore', 1200, 'Tamil,Bengali', 'Other Clinics', TRUE, FALSE, 'https://randomuser.me/api/portraits/women/70.jpg'),
('Dr. Wanda Maximoff', 'Psychiatrist', 'Male', 8, 'Bangalore', 1000, 'Hindi', 'Other Clinics', TRUE, TRUE, 'https://randomuser.me/api/portraits/men/59.jpg'),
('Dr. Scott Lang', 'Dermatologist', 'Male', 18, 'Ahmedabad', 1000, 'Kannada,Bengali', 'Other Clinics', FALSE, TRUE, 'https://randomuser.me/api/portraits/men/49.jpg'),
('Dr. Carol Danvers', 'Gynecologist', 'Female', 23, 'Chennai', 500, 'Urdu,Tamil', 'Apollo Hospital', TRUE, TRUE, 'https://randomuser.me/api/portraits/women/83.jpg'),
('Dr. Nick Fury', 'Cardiologist', 'Male', 3, 'Pune', 1000, 'Hindi,Marathi,Punjabi', 'Other Clinics', FALSE, FALSE, 'https://randomuser.me/api/portraits/men/24.jpg'),
('Dr. Peggy Carter', 'General Physician', 'Female', 22, 'Mumbai', 1200, 'Urdu,Assamese,Bengali', 'Apollo Hospital', FALSE, FALSE, 'https://randomuser.me/api/portraits/women/21.jpg'),
('Dr. Sam Wilson', 'Neurologist', 'Female', 3, 'Delhi', 1200, 'Telugu,Assamese', 'Apollo Hospital', TRUE, TRUE, 'https://randomuser.me/api/portraits/women/95.jpg'),
('Dr. Bucky Barnes', 'Nephrologist', 'Female', 30, 'Mumbai', 700, 'Bengali', 'Apollo Hospital', FALSE, FALSE, 'https://randomuser.me/api/portraits/women/42.jpg'),
('Dr. Challa', 'Orthopedic', 'Female', 4, 'Bangalore', 700, 'Hindi,Kannada,Assamese', 'Other Clinics', TRUE, FALSE, 'https://randomuser.me/api/portraits/women/2.jpg'),
('Dr. Shuri', 'Gynecologist', 'Female', 20, 'Indore', 700, 'Oriya', 'Apollo Hospital', FALSE, TRUE, 'https://randomuser.me/api/portraits/women/12.jpg'),
('Dr. Loki Laufeyson', 'Psychiatrist', 'Male', 25, 'Delhi', 700, 'English,Hindi', 'Other Clinics', TRUE, TRUE, 'https://randomuser.me/api/portraits/men/91.jpg'),
('Dr. Valkyrie', 'Cardiologist', 'Female', 20, 'Kolkata', 500, 'Punjabi', 'Other Clinics', TRUE, TRUE, 'https://randomuser.me/api/portraits/women/71.jpg'),
('Dr. Jane Foster', 'Cardiologist', 'Female', 25, 'Ahmedabad', 1200, 'Marathi,Assamese', 'Other Clinics', FALSE, TRUE, 'https://randomuser.me/api/portraits/women/25.jpg'),
('Dr. Erik Selvig', 'General Physician', 'Male', 30, 'Ahmedabad', 500, 'Hindi,Marathi,Oriya', 'Apollo Hospital', FALSE, FALSE, 'https://randomuser.me/api/portraits/men/70.jpg'),
('Dr. Happy Hogan', 'Gynecologist', 'Female', 1, 'Ahmedabad', 500, 'Urdu,Marathi,Telugu', 'Apollo Hospital', FALSE, TRUE, 'https://randomuser.me/api/portraits/women/16.jpg'),
('Dr. Maria Hill', 'Nephrologist', 'Female', 18, 'Hyderabad', 1000, 'Kannada,Punjabi', 'Apollo Hospital', FALSE, FALSE, 'https://randomuser.me/api/portraits/women/86.jpg'),
('Dr. Pepper Potts', 'Nephrologist', 'Male', 8, 'Delhi', 700, 'Hindi', 'Other Clinics', FALSE, TRUE, 'https://randomuser.me/api/portraits/men/88.jpg'),
('Dr. Darcy Lewis', 'Pediatrician', 'Male', 28, 'Pune', 1000, 'Hindi,Gujarati', 'Other Clinics', FALSE, TRUE, 'https://randomuser.me/api/portraits/men/68.jpg'),
('Dr. Jimmy Woo', 'Neurologist', 'Female', 8, 'Mumbai', 300, 'Telugu,Punjabi', 'Other Clinics', FALSE, FALSE, 'https://randomuser.me/api/portraits/women/22.jpg'),
('Dr. Monica Rambeau', 'Nephrologist', 'Female', 30, 'Ahmedabad', 700, 'Marathi', 'Other Clinics', TRUE, TRUE, 'https://randomuser.me/api/portraits/women/36.jpg'),
('Dr. Kamala Khan', 'Orthopedic', 'Male', 9, 'Ahmedabad', 300, 'Assamese,Gujarati,Persian', 'Apollo Hospital', FALSE, TRUE, 'https://randomuser.me/api/portraits/men/28.jpg'),
('Dr. Kate Bishop', 'Pediatrician', 'Male', 25, 'Hyderabad', 500, 'Urdu,Tamil,Telugu', 'Other Clinics', FALSE, FALSE, 'https://randomuser.me/api/portraits/men/33.jpg'),
('Dr. Yelena Belova', 'Orthopedic', 'Male', 18, 'Chennai', 1200, 'Kannada,Urdu,Gujarati', 'Apollo Hospital', TRUE, FALSE, 'https://randomuser.me/api/portraits/men/86.jpg'),
('Dr. Isaiah Bradley', 'Neurologist', 'Male', 21, 'Chennai', 1200, 'Persian,Assamese,Oriya', 'Apollo Hospital', TRUE, FALSE, 'https://randomuser.me/api/portraits/men/56.jpg'),
('Dr. Agatha Harkness', 'Neurologist', 'Male', 16, 'Mumbai', 700, 'Punjabi', 'Other Clinics', FALSE, FALSE, 'https://randomuser.me/api/portraits/men/43.jpg'),
('Dr. Echo Lopez', 'Gynecologist', 'Female', 21, 'Bangalore', 700, 'Gujarati', 'Other Clinics', FALSE, FALSE, 'https://randomuser.me/api/portraits/women/85.jpg'),
('Dr. Maya Lopez', 'Orthopedic', 'Male', 24, 'Delhi', 500, 'English', 'Other Clinics', FALSE, FALSE, 'https://randomuser.me/api/portraits/men/5.jpg'),
('Dr. Wilson Fisk', 'Neurologist', 'Female', 29, 'Hyderabad', 1000, 'Tamil,Persian', 'Other Clinics', FALSE, TRUE, 'https://randomuser.me/api/portraits/women/98.jpg'),
('Dr. Matt Murdock', 'Dermatologist', 'Male', 25, 'Indore', 500, 'English,Telugu,Oriya', 'Other Clinics', TRUE, TRUE, 'https://randomuser.me/api/portraits/men/56.jpg'),
('Dr. Jessica Jones', 'ENT Specialist', 'Male', 21, 'Surat', 1200, 'Punjabi,Assamese,Persian', 'Other Clinics', TRUE, FALSE, 'https://randomuser.me/api/portraits/men/71.jpg'),
('Dr. Luke Cage', 'ENT Specialist', 'Male', 2, 'Indore', 700, 'English,Assamese,Urdu', 'Apollo Hospital', TRUE, TRUE, 'https://randomuser.me/api/portraits/men/59.jpg'),
('Dr. Danny Rand', 'Gynecologist', 'Male', 9, 'Hyderabad', 1200, 'Urdu,Gujarati,Oriya', 'Apollo Hospital', FALSE, FALSE, 'https://randomuser.me/api/portraits/men/52.jpg'),
('Dr. Frank Castle', 'Nephrologist', 'Male', 15, 'Bangalore', 1200, 'Hindi', 'Apollo Hospital', TRUE, TRUE, 'https://randomuser.me/api/portraits/men/18.jpg'),
('Dr. Elektra Natchios', 'Dermatologist', 'Male', 24, 'Kolkata', 500, 'Urdu', 'Other Clinics', FALSE, TRUE, 'https://randomuser.me/api/portraits/men/95.jpg'),
('Dr. Gwen Stacy', 'General Physician', 'Male', 26, 'Delhi', 300, 'Bengali,Marathi', 'Apollo Hospital', TRUE, TRUE, 'https://randomuser.me/api/portraits/men/47.jpg'),
('Dr. Miles Morales', 'Pediatrician', 'Female', 26, 'Surat', 1200, 'Telugu', 'Other Clinics', TRUE, FALSE, 'https://randomuser.me/api/portraits/women/51.jpg'),
('Dr. Otto Octavius', 'Cardiologist', 'Male', 13, 'Pune', 300, 'Tamil', 'Apollo Hospital', FALSE, TRUE, 'https://randomuser.me/api/portraits/men/19.jpg');